name: Publish site

on:
  push:
    paths: 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.120.4'
          extended: true

      - name: Build
        run: hugo --minify --source src

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: ${{ vars.TARGET_REPO }}
          publish_branch: main
          cname: ${{ vars.SITE_CNAME }}
          publish_dir: ./src/public